### ISSUE TITLE
Type hinting generics only in Python >= 3.9

### ISSUE THREAD

**Issue by jpmcfarland** [chStaiger/iBridges-Gui#99]
Generic type hinting of classes with a subscript is very handy:

```python
    def get_diff_upload(self,
                        source: Union[str, Path],
                        target: Union[iRODSDataObject, iRODSCollection, str],
                        arguments: str = None) -> list[SyncResult]:
```

but is not supported below Python 3.9.  Removing support for Python < 3.9 is not possible as many mainstream Linux distributions don't allow Python > 3.8 out of the box.

What should be done?

**Comment by chStaiger** [comment]
Then I would opt for making 3.9 our default python environment. Since @maartenschermer already rewrote the icommands backend to make use **only**of the icommands we can then cater for two scenarios:

1. Install python 3.9 on your operating system (Windows and Mac need that anyways)
2. install the icommands on your operating system (we then restrict our GUI to linux distress that are supported by the iRODS consortium)

Would that be enough?

**Comment by jpmcfarland** [comment]
I think limiting it to iRODS-supported distributions is indeed a good idea.  I'm just concerned that users of Linux distributions that require either a third-party APT/YUM repository or manual compilation to have Python >= 3.9 may be put off.  We should give explicit instructions regardless.

Also, such a requirement is not without potential problems.  On a very recent version of LinuxMint (Ubuntu-derived), I had to install an extra library for PyQt to get iBridges to run with Python > 3.8.  In itself, not a problem, but trying to figure out that solution from a cryptic error message was not easy.  Certainly not something your average data scientist is likely to want to do unless they are very motivated.
